mutation(
$target_message_id: ID!
$target_type: EnumMessage!
$content: String
$img_url: String
$uid: ID!
$operate_time: DateTime!
) {
  createDiscuss(
    data: {
      target_type: $target_type
      target_message_id: $target_message_id
      content: $content
      operate_time: $operate_time
      img_url: $img_url
      operator: { connect: { school_id: "16121663" } }
    }
  ) {
    type: __typename
    id
    content
    operate_time
    img_url
    liked_num
    replyed_num
    operator {
      id
      nickname
      avatar
    }
    like(where: { operator: { id: $uid } }) {
      liked
    }
    discuss(first: 3, orderBy: liked_num_DESC) {
      id
      type: __typename
      content
      operator {
        id
        nickname
      }
    }
  }
}
