query($target_message_id: ID!, $uid: ID!) {
  hotDiscusses: discusses(
    first: 5
    where: {
      target_type: NEWS
      target_message_id: $target_message_id
      liked_num_gte: 1
    }
    orderBy: liked_num_DESC
  ) {
    type:__typename
    id
    content
    operate_time
    img_url
    liked_num
    replyed_num
    operator {
      id
      nickname
      avatar
    }
    like(where: { operator: { id: $uid } }) {
      liked
    }
    discuss(first: 3, orderBy: liked_num_DESC) {
      id
      type: __typename
      content
      operator {
        id
        nickname
      }
    }
  }
}
