query($after: String, $uid: ID!){
  newses(after: $after, first:20) {
    type: __typename
    id
    description
    publish_time
    media_type
    media_title
    media_url
    media_img
    publisher {
      id
      nickname
      avatar
    }
    shared_num
    comment_num
    liked_num
    labels {
      name
    }
    publish_time
    like(where: { operator: { id: $uid } }) {
      liked
    }
    share(where: { operator: { id: $uid } }) {
      id
    }
    discuss(where: { operator: { id: $uid } }) {
      id
    }
  }
}
